// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlthfiClZNEuLfu52zSB69Ds9hUuK4o50',
    appId: '1:425278799522:web:e8f0d630d4f4e187f161fb',
    messagingSenderId: '425278799522',
    projectId: 'pcos-wellness-app-e202a',
    authDomain: 'pcos-wellness-app-e202a.firebaseapp.com',
    storageBucket: 'pcos-wellness-app-e202a.firebasestorage.app',
    measurementId: 'G-ZLRYLPK66J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGch0elVTjKHM3mOsfbxweB7YhPKSduh4',
    appId: '1:425278799522:android:76aa4dbb2d5f5410f161fb',
    messagingSenderId: '425278799522',
    projectId: 'pcos-wellness-app-e202a',
    storageBucket: 'pcos-wellness-app-e202a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtkXaRYEaJAljrMrJCiu4vqtnhfuee8kE',
    appId: '1:425278799522:ios:4acaa29e28a419c7f161fb',
    messagingSenderId: '425278799522',
    projectId: 'pcos-wellness-app-e202a',
    storageBucket: 'pcos-wellness-app-e202a.firebasestorage.app',
    iosBundleId: 'com.alyshaanne.pcosWellness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtkXaRYEaJAljrMrJCiu4vqtnhfuee8kE',
    appId: '1:425278799522:ios:4acaa29e28a419c7f161fb',
    messagingSenderId: '425278799522',
    projectId: 'pcos-wellness-app-e202a',
    storageBucket: 'pcos-wellness-app-e202a.firebasestorage.app',
    iosBundleId: 'com.alyshaanne.pcosWellness',
  );
}
